#!/bin/sh
#
# Run the docs build process, producing `build/latest` instead of
# `docs/_build`. Can be extended to also build `stable`.

set -e


# TEMPORARY: override this for CI testing
#latest_branch=main
latest_branch=k8s-container

do_build() {
    git checkout "$1"

    make html
    # If at some point this fails, see securedrop-docs for a workaround
    make latexpdf

    mkdir -p build
    mv docs/_build "build/${2}"
}

export SECUREDROP_DOCS_RELEASE=latest
do_build "$latest_branch" latest
